name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  l10n-github-login:  # github login for l10n
    description: 'login for l10n'
    required: true
  github-token:
    description: 'github token with access to the repo'
    required: true
outputs:
  time: # id of output
    description: 'Time the action was run'
runs:
  using: 'node16'
  main: 'index.js'